@startuml DatabaseCommManagerImplementation

package edu.oakland.production.database {
    class DatabaseCommManagerImplementation {
        - DatabasePersistentStorage databasePersistentStorage
        __
        + DatabaseCommManagerImplementation(DatabasePersistentStorage databasePersistentStorage)
        .. Use Case 1 ..
        + int passGetRfidRequest()
        + LocationDataPoint passGetLocationDataPointRequest(int offset)
        + TrackData passGetTrackDataRequest(int offset)
        + void passStoreTrackDataRequest(TrackData trackData)
    }
}

@enduml
