@startuml DatabaseCommManagerImplementation_Closure

!startsub DATABASE_PRODUCTION
!include DatabaseCommManagerImplementation.puml

!include ../DatabaseCommManager/DatabaseCommManager_Closure.puml
DatabaseCommManagerImplementation .up.|> DatabaseCommManager
!endsub

!startsub DATABASE

!endsub

!startsub OTHER

!endsub

@enduml