@startuml DatabaseGisPersistentStorage

package edu.oakland.production.database01 {
    interface DatabaseGisPersistentStorage {
        __
        .. Use Case 1 ..
        {abstract} + void storeLocation(LocationDataPoint locationDataPoint)
        .. Use Case 2 ..
        {abstract} + void storeMode(String mode)
        {abstract} + String getNextSat(String currentSat)
    }
}

@enduml