@startuml DatabaseGisPersistentStorageImplementation_DirectDependencies

!startsub DATABASE01_PRODUCTION
!include DatabaseGisPersistentStorageImplementation.puml

!include ../DatabaseGisPersistentStorage/DatabaseGisPersistentStorage.puml
DatabaseGisPersistentStorageImplementation .up.|> DatabaseGisPersistentStorage
!endsub

!startsub DATABASE01

!endsub

!startsub OTHER

!endsub

@enduml