@startuml DisplayGpsInterfaceImplementation_Closure

!startsub DISPLAY01_PRODUCTION
!include DisplayGpsInterfaceImplementation.puml

!include ../DisplayGpsInterface/DisplayGpsInterface_Closure.puml
DisplayGpsInterfaceImplementation .up.|> DisplayGpsInterface
!endsub

!startsub DISPLAY01
!include ../../helper/SatelliteSignalCheckRequest/SatelliteSignalCheckRequest_Closure.puml
DisplayGpsInterfaceImplementation ..> SatelliteSignalCheckRequest
!endsub

!startsub OTHER

!endsub

@enduml