@startuml DisplayGpsInterfaceImplementation

package edu.oakland.production.display01 {
    class DisplayGpsInterfaceImplementation {
        __
        .. Use Case 1 ..

        .. Use Case 2 ..

    }
}

@enduml