@startuml DatabaseHelperPackage_InternalDependencies

package edu.oakland.helper.database {
    
}

!includesub PersistentStorageManager/PersistentStorageManager_DirectDependencies.puml!DATABASE_HELPER

@enduml