@startuml DisplayCommManagerImplementation

package edu.oakland.production.display02 {
    class DisplayCommManagerImplementation {
        __
        .. Use Case 1 ..

        .. Use Case 2 ..

    }
}

@enduml