@startuml DisplayCommManagerImplementation_Closure

!startsub DISPLAY02_PRODUCTION
!include DisplayCommManagerImplementation.puml

!include ../DisplayCommManager/DisplayCommManager_Closure.puml
DisplayCommManagerImplementation .up.|> DisplayCommManager
!endsub

!startsub DISPLAY02

!endsub

!startsub OTHER

!endsub

@enduml