@startuml SatelliteTests

package edu.oakland.test.admin {
    class SatelliteTests {
       + void satNameInIsSatNameOut()
       + void strengthInIsStrengthOutConstructor()
       + void strengthInIsStrengthOutSetter()
       + void getLocation0IsCorrect()
       + void getLocation1IsCorrect()
       + void getLocationNIsCorrect()
       + void getLocationAcrossMultipleObjectsInSync()
       + void strengthNotLessThanOneConstructor()
       + void strengthNotMoreThanTenConstructor()
       + void strengthNotLessThanOneSetter()
       + void strengthNotMoreThanTenSetter()
    }
}

@enduml
