@startuml SatelliteTests_DirectDependencies

!startsub ADMIN_TEST
!include SatelliteTests.puml
!endsub

!startsub ADMIN
!include ../../helper/Satellite/Satellite.puml
SatelliteTests ..> Satellite
!endsub

!startsub OTHER

!endsub

@enduml