@startuml DatabaseGisInterfaceImplementation_DirectDependencies

!startsub DATABASE01_PRODUCTION
!include DatabaseGisInterfaceImplementation.puml

!include ../DatabaseGisInterface/DatabaseGisInterface.puml
DatabaseGisInterfaceImplementation .up.|> DatabaseGisInterface
!endsub

!startsub DATABASE01

!endsub

!startsub OTHER

!endsub

@enduml