@startuml Middleware01ProductionPackage_DirectDependencies

package edu.oakland.production.middleware01 {
    
}

!startsub MIDDLEWARE01
!include Middleware01ProductionPackage_InternalDependencies.puml
!includesub MiddlewareGisInterface/MiddlewareGisInterface_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisProcessor/MiddlewareGisProcessor_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisManager/MiddlewareGisManager_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisInterfaceImplementation/MiddlewareGisInterfaceImplementation_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisProcessorImplementation/MiddlewareGisProcessorImplementation_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisManagerImplementation/MiddlewareGisManagerImplementation_DirectDependencies.puml!MIDDLEWARE01
!endsub

!includesub MiddlewareGisInterface/MiddlewareGisInterface_DirectDependencies.puml!OTHER
!includesub MiddlewareGisProcessor/MiddlewareGisProcessor_DirectDependencies.puml!OTHER
!includesub MiddlewareGisManager/MiddlewareGisManager_DirectDependencies.puml!OTHER
!includesub MiddlewareGisInterfaceImplementation/MiddlewareGisInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub MiddlewareGisProcessorImplementation/MiddlewareGisProcessorImplementation_DirectDependencies.puml!OTHER
!includesub MiddlewareGisManagerImplementation/MiddlewareGisManagerImplementation_DirectDependencies.puml!OTHER

@enduml