@startuml Middleware01ProductionPackage_InternalDependencies

package edu.oakland.production.middleware01 {
    
}

!includesub MiddlewareGisInterface/MiddlewareGisInterface_DirectDependencies.puml!MIDDLEWARE01_PRODUCTION
!includesub MiddlewareGisProcessor/MiddlewareGisProcessor_DirectDependencies.puml!MIDDLEWARE01_PRODUCTION
!includesub MiddlewareGisManager/MiddlewareGisManager_DirectDependencies.puml!MIDDLEWARE01_PRODUCTION
!includesub MiddlewareGisInterfaceImplementation/MiddlewareGisInterfaceImplementation_DirectDependencies.puml!MIDDLEWARE01_PRODUCTION
!includesub MiddlewareGisProcessorImplementation/MiddlewareGisProcessorImplementation_DirectDependencies.puml!MIDDLEWARE01_PRODUCTION
!includesub MiddlewareGisManagerImplementation/MiddlewareGisManagerImplementation_DirectDependencies.puml!MIDDLEWARE01_PRODUCTION

@enduml