@startuml Satellite_Closure

!startsub ADMIN_HELPER
!include Satellite.puml

!include ../LocationDataPoint/LocationDataPoint_Closure.puml
Satellite *--> LocationDataPoint
!endsub

!startsub ADMIN

!endsub

!startsub OTHER

!endsub

@enduml