@startuml Satellite_DirectDependencies

!startsub ADMIN_HELPER
!include Satellite.puml

!include ../LocationDataPoint/LocationDataPoint.puml
Satellite *--> LocationDataPoint
!endsub

!startsub ADMIN

!endsub

!startsub OTHER

!endsub

@enduml