@startuml DatabaseGisManagerImplementation_Closure

!startsub DATABASE_PRODUCTION
!include DatabaseGisManagerImplementation.puml

!include ../DatabaseGisManager/DatabaseGisManager_Closure.puml
DatabaseGisManagerImplementation .up.|> DatabaseGisManager
!endsub

!startsub DATABASE

!endsub

!startsub OTHER

!endsub

@enduml