@startuml DatabaseGisManagerImplementation

package edu.oakland.production.database {
    class DatabaseGisManagerImplementation {
        - LocationDataPoint locDataPoint
        - String mode
        - String currentSat
        __
        + DatabaseGisManagerImplementation(
        \tDatabasePersistentStorage databasePersistentStorage)
        .. Use Case 1 ..
        + void passStoreRequest(LocationDataPoint locationDataPoint)
        .. Use Case 2 ..
        + void passModeRequest(String mode)
        + String passNextSatRequest(String currentSat)
    }
}

@enduml
