@startuml DisplayGpsManagerStub_DirectDependencies

!startsub DISPLAY01_TEST
!include DisplayGpsManagerStub.puml
!endsub

!startsub DISPLAY01
!include ../../production/DisplayGpsManager/DisplayGpsManager.puml
DisplayGpsManagerStub .up.|> DisplayGpsManager
!endsub

!startsub OTHER

!endsub

@enduml