@startuml DisplayGpsReceiverImplementation

package edu.oakland.production.display01 {
    class DisplayGpsReceiverImplementation {
        - DisplayGpsManager manager
        __
        + DisplayGpsReceiverImplementation(DisplayGpsManager manager)
        .. Use Case 1 ..
        + String measureGpsSignalStrength(Satellite satelliteSignal)
        - void passSignalStrength(int signalStrength)
        .. Use Case 2 ..
        + String measureGpsSignalStrength(Satellite satelliteSignal)
        + SatelliteSignalCheckRequest measureSignal(String satelliteName)
    }
}

@enduml
