@startuml DisplayGpsReceiverImplementation_DirectDependencies

!startsub DISPLAY01_PRODUCTION
!include DisplayGpsReceiverImplementation.puml

!include ../DisplayGpsReceiver/DisplayGpsReceiver.puml
DisplayGpsReceiverImplementation .up.|> DisplayGpsReceiver
!endsub

!startsub DISPLAY01

!endsub

!startsub OTHER

!endsub

@enduml