@startuml DisplayGpsReceiverImplementation_DirectDependencies

!startsub DISPLAY01_PRODUCTION
!include DisplayGpsReceiverImplementation.puml

!include ../DisplayGpsReceiver/DisplayGpsReceiver.puml
DisplayGpsReceiverImplementation .up.|> DisplayGpsReceiver
!endsub

!startsub DISPLAY01
!include ../../helper/SatelliteSignalCheckRequest/SatelliteSignalCheckRequest.puml
DisplayGpsReceiverImplementation ..> SatelliteSignalCheckRequest
!endsub

!startsub OTHER

!endsub

@enduml