@startuml DatabaseCommPersistentStorageImplementation

package edu.oakland.production.database02 {
    class DatabaseCommPersistentStorageImplementation {
        __
        .. Use Case 1 ..

        .. Use Case 2 ..

    }
}

@enduml