@startuml SatelliteSignalCheckRequest

package edu.oakland.helper.display01 {
    class SatelliteSignalCheckRequest {
        - String satelliteName
        - String checkType
        + SatelliteSignalCheckRequest(String satelliteName, String checkType)
        + String getSatelliteName()
        + String getCheckType()
    }
}

@enduml