@startuml MiddlewareCommDatabaseInterfaceImplementationTests

package edu.oakland.test.middleware02 {
    class MiddlewareCommDatabaseInterfaceImplementationTests {
        + void rfidInIsRfidOut()
        + void databaseCommInterfaceIsNotNull()
    }
}

@enduml
