@startuml DatabaseCommManagerImplementation_DirectDependencies

!startsub DATABASE02_PRODUCTION
!include DatabaseCommManagerImplementation.puml

!include ../DatabaseCommManager/DatabaseCommManager.puml
DatabaseCommManagerImplementation .up.|> DatabaseCommManager
!endsub

!startsub DATABASE02

!endsub

!startsub OTHER

!endsub

@enduml