@startuml Database02ProductionPackage_DirectDependencies

package edu.oakland.production.database02 {
    
}

!startsub DATABASE02
!include Database02ProductionPackage_InternalDependencies.puml
!includesub DatabaseCommInterface/DatabaseCommInterface_DirectDependencies.puml!DATABASE02
!includesub DatabaseCommManager/DatabaseCommManager_DirectDependencies.puml!DATABASE02
!includesub DatabaseCommPersistentStorage/DatabaseCommPersistentStorage_DirectDependencies.puml!DATABASE02
!includesub DatabaseCommInterfaceImplementation/DatabaseCommInterfaceImplementation_DirectDependencies.puml!DATABASE02
!includesub DatabaseCommManagerImplementation/DatabaseCommManagerImplementation_DirectDependencies.puml!DATABASE02
!includesub DatabaseCommPersistentStorageImplementation/DatabaseCommPersistentStorageImplementation_DirectDependencies.puml!DATABASE02
!endsub

!includesub DatabaseCommInterface/DatabaseCommInterface_DirectDependencies.puml!OTHER
!includesub DatabaseCommManager/DatabaseCommManager_DirectDependencies.puml!OTHER
!includesub DatabaseCommPersistentStorage/DatabaseCommPersistentStorage_DirectDependencies.puml!OTHER
!includesub DatabaseCommInterfaceImplementation/DatabaseCommInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub DatabaseCommManagerImplementation/DatabaseCommManagerImplementation_DirectDependencies.puml!OTHER
!includesub DatabaseCommPersistentStorageImplementation/DatabaseCommPersistentStorageImplementation_DirectDependencies.puml!OTHER

@enduml