@startuml Database02ProductionPackage_InternalDependencies

package edu.oakland.production.database02 {
    
}

!includesub DatabaseCommInterface/DatabaseCommInterface_DirectDependencies.puml!DATABASE02_PRODUCTION
!includesub DatabaseCommManager/DatabaseCommManager_DirectDependencies.puml!DATABASE02_PRODUCTION
!includesub DatabaseCommPersistentStorage/DatabaseCommPersistentStorage_DirectDependencies.puml!DATABASE02_PRODUCTION
!includesub DatabaseCommInterfaceImplementation/DatabaseCommInterfaceImplementation_DirectDependencies.puml!DATABASE02_PRODUCTION
!includesub DatabaseCommManagerImplementation/DatabaseCommManagerImplementation_DirectDependencies.puml!DATABASE02_PRODUCTION
!includesub DatabaseCommPersistentStorageImplementation/DatabaseCommPersistentStorageImplementation_DirectDependencies.puml!DATABASE02_PRODUCTION

@enduml