@startuml DatabaseGisManagerImplementation_DirectDependencies

!startsub DATABASE01_PRODUCTION
!include DatabaseGisManagerImplementation.puml

!include ../DatabaseGisManager/DatabaseGisManager.puml
DatabaseGisManagerImplementation .up.|> DatabaseGisManager
!endsub

!startsub DATABASE01

!endsub

!startsub OTHER

!endsub

@enduml