@startuml DatabaseCommManagerImplementationTests

package edu.oakland.test.database {
    class DatabaseCommManagerImplementationTests {
        + void rfidInIsRfidOut()
        + void offsetMatchDataPoint()
        + void offsetMatchTrackData()
        + void trackDataInIsTrackDataOut()
        + void databasePersistentStorageIsNotNull() 
    }
}

@enduml
