@startuml MiddlewareCommDatabaseInterfaceImplementation_Closure

!startsub MIDDLEWARE02_PRODUCTION
!include MiddlewareCommDatabaseInterfaceImplementation.puml

!include ../MiddlewareCommDatabaseInterface/MiddlewareCommDatabaseInterface_Closure.puml
MiddlewareCommDatabaseInterfaceImplementation .up.|> MiddlewareCommDatabaseInterface
!endsub

!startsub MIDDLEWARE02

!endsub

!startsub OTHER

!endsub

@enduml