@startuml MiddlewareCommDatabaseInterfaceImplementation

package edu.oakland.production.middleware02 {
    class MiddlewareCommDatabaseInterfaceImplementation {
        + DatabaseCommInterface databaseCommInterface
        __
        + MiddlewareCommDatabaseInterfaceImplementation(
        \tDatabaseCommInterface databaseCommInterface)
        .. Use Case 1 ..
        + int checkCurrentRfid()
    }
}

@enduml