@startuml TrackDataTests_DirectDependencies

!startsub ADMIN_TEST
!include TrackDataTests.puml
!endsub

!startsub ADMIN
!include ../../helper/TrackData/TrackData.puml
TrackDataTests ..> TrackData
!endsub

!startsub OTHER

!endsub

@enduml