@startuml TrackDataTests

package edu.oakland.test.admin {
    class TrackDataTests {
        + void pointsOnlyConstructorCourseIs0()
        + void fullDataConstructorcourseInIsCourseOut()
        + void pointsOnlyConstructorSpeedIs0()
        + void fullDataConstructorspeedInIsSpeedOut()
        + void pointsOnlyConstructorValidFalse()
        + void fullDataConstructorValidTrue()
        + void pointsOnlyConstructorPointsInArePointsOut()
        + void fullDataConstructorPointsInArePointsOut()
        + void noValidDataViaPointsOnlyConstructor()
        + void noNullDataViaPointsOnlyConstructor()
        + void noNullDataViaFullDataConstructor()
        + void noTooLittleDataViaFullDataConstructor()
        + void noTooMuchDataViaFullDataConstructor()
        + void noNegativeSpeedViaFullDataConstructor()
        + void noNegativeCourseViaFullDataConstructor()
        + void noTooLargeCourseViaFullDataConstructor()
    }
}

@enduml