@startuml MiddlewareCommLinkManager_DirectDependencies

!startsub MIDDLEWARE02_PRODUCTION
!include MiddlewareCommLinkManager.puml
!endsub

!startsub MIDDLEWARE02

!endsub

!startsub OTHER

!endsub

@enduml