@startuml PersistentStorageManagerTests_Closure

!startsub DATABASE_TEST
!include PersistentStorageManagerTests.puml
!endsub

!startsub DATABASE
!include ../../helper/PersistentStorageManager/PersistentStorageManager_Closure.puml
PersistentStorageManagerTests ..> PersistentStorageManager
!endsub

!startsub OTHER

!endsub

@enduml