@startuml PersistentStorageManagerTests

package edu.oakland.test.database {
    class PersistentStorageManagerTests {
        + void readDataInIsDataOut()
        + void writeDataInIsDataOut()
        + void correctDeserialization()
        + void correctSerialization()
    }
}

@enduml