@startuml MiddlewareCommDatabaseInterface

package edu.oakland.production.middleware02 {
    interface MiddlewareCommDatabaseInterface {
        __
        .. Use Case 1 ..
        {abstract} + int checkCurrentRfid()
        .. Use Case 2 ..

    }
}

@enduml