@startuml MiddlewareCommLinkManagerImplementationTests

package edu.oakland.test.middleware02 {
    class MiddlewareCommLinkManagerImplementationTests {
      + void verifyTrackLengthTest()
      + void rfidInIsRfidOut()
      + void gpsDataInIsGpsDataOut()
    
    }
}

@enduml