@startuml GpsSystemTests_Closure

!startsub ADMIN_TEST
!include GpsSystemTests.puml

!include ../DisplayGpsInterfaceStub/DisplayGpsInterfaceStub_Closure.puml
GpsSystemTests ..> DisplayGpsInterfaceStub
!endsub

!startsub ADMIN
!include ../../production/GpsSystem/GpsSystem_Closure.puml
GpsSystemTests ..> GpsSystem
!endsub

!startsub OTHER

!endsub

@enduml