@startuml DatabaseCommInterfaceImplementation_DirectDependencies

!startsub DATABASE_PRODUCTION
!include DatabaseCommInterfaceImplementation.puml

!include ../DatabaseCommInterface/DatabaseCommInterface.puml
DatabaseCommInterfaceImplementation .up.|> DatabaseCommInterface
!endsub

!startsub DATABASE

!endsub

!startsub OTHER

!endsub

@enduml