@startuml DatabaseCommInterfaceImplementation_Closure

!startsub DATABASE_PRODUCTION
!include DatabaseCommInterfaceImplementation.puml

!include ../DatabaseCommInterface/DatabaseCommInterface_Closure.puml
DatabaseCommInterfaceImplementation .up.|> DatabaseCommInterface
!endsub

!startsub DATABASE

!endsub

!startsub OTHER

!endsub

@enduml