@startuml DisplayGpsReceiverStub

package edu.oakland.test.display01 {
    class DisplayGpsReceiverStub {
        __
        .. Use Case 1 ..
        + String measureGpsSignalStrength(Satellite satelliteSignal)
        .. Use Case 2 ..
        + SatelliteSignalCheckRequest measureSignal(String satelliteName)
    }
}

@enduml