@startuml MiddlewareCommInterfaceImplementation_DirectDependencies

!startsub MIDDLEWARE02_PRODUCTION
!include MiddlewareCommInterfaceImplementation.puml

!include ../MiddlewareCommInterface/MiddlewareCommInterface.puml
MiddlewareCommInterfaceImplementation .up.|> MiddlewareCommInterface
!endsub

!startsub MIDDLEWARE02

!endsub

!startsub OTHER

!endsub

@enduml