@startuml Database01ProductionPackage_InternalDependencies

package edu.oakland.production.database01 {
    
}

!includesub DatabaseGisInterface/DatabaseGisInterface_DirectDependencies.puml!DATABASE01_PRODUCTION
!includesub DatabaseGisManager/DatabaseGisManager_DirectDependencies.puml!DATABASE01_PRODUCTION
!includesub DatabaseGisPersistentStorage/DatabaseGisPersistentStorage_DirectDependencies.puml!DATABASE01_PRODUCTION
!includesub DatabaseGisInterfaceImplementation/DatabaseGisInterfaceImplementation_DirectDependencies.puml!DATABASE01_PRODUCTION
!includesub DatabaseGisManagerImplementation/DatabaseGisManagerImplementation_DirectDependencies.puml!DATABASE01_PRODUCTION
!includesub DatabaseGisPersistentStorageImplementation/DatabaseGisPersistentStorageImplementation_DirectDependencies.puml!DATABASE01_PRODUCTION

@enduml