@startuml DatabasePackages_DirectDependencies

!include production/DatabaseProductionPackage_DirectDependencies.puml
!include test/DatabaseTestPackage_DirectDependencies.puml
!include helper/DatabaseHelperPackage_InternalDependencies.puml

@enduml