@startuml MiddlewareGisProcessorImplementationTests

package edu.oakland.test.middleware01 {
  class MiddlewareGisProcessorImplementationTests {
    + void evaluateGpsSignalStrength()
    + void measureGpsSignalStrength()
  }
}

@enduml