@startuml MiddlewareCommInterfaceImplementationTests

package edu.oakland.test.middleware02 {
    class MiddlewareCommInterfaceImplementationTests {
        + void rfidInIsRfidOut()
        + void MiddlewareCommLinkManagerIsNotNull()
    }
}

@enduml