@startuml Display01TestPackage_InternalDependencies

package edu.oakland.test.display01 {
    
}

!includesub DisplayGpsInterfaceImplementationTests/DisplayGpsInterfaceImplementationTests_DirectDependencies.puml!DISPLAY01_TEST
!includesub DisplayGpsReceiverImplementationTests/DisplayGpsReceiverImplementationTests_DirectDependencies.puml!DISPLAY01_TEST
!includesub DisplayGpsManagerImplementationTests/DisplayGpsManagerImplementationTests_DirectDependencies.puml!DISPLAY01_TEST
!includesub SatelliteSignalCheckRequestTests/SatelliteSignalCheckRequestTests_DirectDependencies.puml!DISPLAY01_TEST
!includesub DisplayGpsReceiverStub/DisplayGpsReceiverStub_DirectDependencies.puml!DISPLAY01_TEST
!includesub DisplayGpsManagerStub/DisplayGpsManagerStub_DirectDependencies.puml!DISPLAY01_TEST
!includesub MiddlewareGisInterfaceStub/MiddlewareGisInterfaceStub_DirectDependencies.puml!DISPLAY01_TEST

@enduml