@startuml Display01TestPackage_DirectDependencies

package edu.oakland.test.display01 {
    
}

!startsub DISPLAY01
!include Display01TestPackage_InternalDependencies.puml
!includesub DisplayGpsInterfaceImplementationTests/DisplayGpsInterfaceImplementationTests_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsReceiverImplementationTests/DisplayGpsReceiverImplementationTests_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsManagerImplementationTests/DisplayGpsManagerImplementationTests_DirectDependencies.puml!DISPLAY01
!includesub SatelliteSignalCheckRequestTests/SatelliteSignalCheckRequestTests_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsReceiverStub/DisplayGpsReceiverStub_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsManagerStub/DisplayGpsManagerStub_DirectDependencies.puml!DISPLAY01
!includesub MiddlewareGisInterfaceStub/MiddlewareGisInterfaceStub_DirectDependencies.puml!DISPLAY01
!endsub

!includesub DisplayGpsInterfaceImplementationTests/DisplayGpsInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub DisplayGpsReceiverImplementationTests/DisplayGpsReceiverImplementationTests_DirectDependencies.puml!OTHER
!includesub DisplayGpsManagerImplementationTests/DisplayGpsManagerImplementationTests_DirectDependencies.puml!OTHER
!includesub SatelliteSignalCheckRequestTests/SatelliteSignalCheckRequestTests_DirectDependencies.puml!OTHER
!includesub DisplayGpsReceiverStub/DisplayGpsReceiverStub_DirectDependencies.puml!OTHER
!includesub DisplayGpsManagerStub/DisplayGpsManagerStub_DirectDependencies.puml!OTHER
!includesub MiddlewareGisInterfaceStub/MiddlewareGisInterfaceStub_DirectDependencies.puml!OTHER

@enduml