@startuml Display02ProductionPackage_DirectDependencies

package edu.oakland.production.display02 {
    
}

!startsub DISPLAY02
!include Display02ProductionPackage_InternalDependencies.puml
!includesub DisplayCommInterface/DisplayCommInterface_DirectDependencies.puml!DISPLAY02
!includesub DisplayComm2WayInterface/DisplayComm2WayInterface_DirectDependencies.puml!DISPLAY02
!includesub DisplayCommManager/DisplayCommManager_DirectDependencies.puml!DISPLAY02
!includesub DisplayCommInterfaceImplementation/DisplayCommInterfaceImplementation_DirectDependencies.puml!DISPLAY02
!includesub DisplayComm2WayInterfaceImplementation/DisplayComm2WayInterfaceImplementation_DirectDependencies.puml!DISPLAY02
!includesub DisplayCommManagerImplementation/DisplayCommManagerImplementation_DirectDependencies.puml!DISPLAY02
!endsub

!includesub DisplayCommInterface/DisplayCommInterface_DirectDependencies.puml!OTHER
!includesub DisplayComm2WayInterface/DisplayComm2WayInterface_DirectDependencies.puml!OTHER
!includesub DisplayCommManager/DisplayCommManager_DirectDependencies.puml!OTHER
!includesub DisplayCommInterfaceImplementation/DisplayCommInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub DisplayComm2WayInterfaceImplementation/DisplayComm2WayInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub DisplayCommManagerImplementation/DisplayCommManagerImplementation_DirectDependencies.puml!OTHER

@enduml