@startuml MiddlewareGisInterfaceImplementation_Closure

!startsub MIDDLEWARE01_PRODUCTION
!include MiddlewareGisInterfaceImplementation.puml

!include ../MiddlewareGisInterface/MiddlewareGisInterface_Closure.puml
MiddlewareGisInterfaceImplementation .up.|> MiddlewareGisInterface
!endsub

!startsub MIDDLEWARE01

!endsub

!startsub OTHER

!endsub

@enduml