@startuml MiddlewareGisInterfaceImplementation

package edu.oakland.production.middleware01 {
    class MiddlewareGisInterfaceImplementation {
        __
        .. Use Case 1 ..

        .. Use Case 2 ..

    }
}

@enduml