@startuml MiddlewareGisInterfaceImplementation

package edu.oakland.production.middleware01 {
    class MiddlewareGisInterfaceImplementation {
        - MiddlewareGisProcessor middlewareGisProcessor
        __
        + MiddlewareGisInterfaceImplementation(MiddlewareGisProcessor middlewareGisProcessor)
        .. Use Case 1 ..
        + String receiveGpsSignalStrength(Satellite satelliteSignal)
        .. Use Case 2 ..
        + String receiveGpsSignalStrength(Satellite satelliteSignal)
    }
}

@enduml