@startuml User

package edu.oakland.production.admin {
    class User {
        - DisplayCommInterface displayCommInterface
        + User(DisplayCommInterface displayCommInterface)
        + void runUseCase1(Scanner input)
    }
}

@enduml