@startuml DatabaseCommInterfaceStub_DirectDependencies

!startsub MIDDLEWARE02_TEST
!include DatabaseCommInterfaceStub.puml
!endsub

!startsub MIDDLEWARE02

!endsub

!startsub OTHER
!include ../../../database/production/DatabaseCommInterface/DatabaseCommInterface.puml
DatabaseCommInterfaceStub .up.|> DatabaseCommInterface
!endsub

@enduml