@startuml DisplayCommInterface

package edu.oakland.production.display02 {
    interface DisplayCommInterface {
        __
        .. Use Case 1 ..
        {abstract} + TrackData receiveRfidRequest(int rfidNum)

        .. Use Case 2 ..

    }
}

@enduml
