@startuml DisplayCommManagerStub

package edu.oakland.test.display02 {
    class DisplayCommManagerStub {
        __
        .. Use Case 1 ..
        + TrackData evaluateRfidRequest(int rfidNum)
    }
}

@enduml