@startuml Middleware02HelperPackage_InternalDependencies

package edu.oakland.helper.middleware02 {
    
}

!includesub TrackDataCalculator/TrackDataCalculator_DirectDependencies.puml!MIDDLEWARE02_HELPER

@enduml