@startuml PersistentStorageManager_DirectDependencies

!startsub DATABASE_HELPER
!include PersistentStorageManager.puml
!endsub

!startsub DATABASE
!include ../../production/DatabasePersistentStorageImplementation/DatabasePersistentStorageImplementation.puml
PersistentStorageManager --> DatabasePersistentStorageImplementation
!endsub

!startsub OTHER

!endsub

@enduml