@startuml DatabaseCommPersistentStorage_DirectDependencies

!startsub DATABASE02_PRODUCTION
!include DatabaseCommPersistentStorage.puml
!endsub

!startsub DATABASE02

!endsub

!startsub OTHER

!endsub

@enduml