@startuml Middleware02ProductionPackage_DirectDependencies

package edu.oakland.production.middleware02 {
    
}

!startsub MIDDLEWARE02
!include Middleware02ProductionPackage_InternalDependencies.puml
!includesub MiddlewareCommInterface/MiddlewareCommInterface_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommLinkManager/MiddlewareCommLinkManager_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommDatabaseInterface/MiddlewareCommDatabaseInterface_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommInterfaceImplementation/MiddlewareCommInterfaceImplementation_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommLinkManagerImplementation/MiddlewareCommLinkManagerImplementation_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommDatabaseInterfaceImplementation/MiddlewareCommDatabaseInterfaceImplementation_DirectDependencies.puml!MIDDLEWARE02
!endsub

!includesub MiddlewareCommInterface/MiddlewareCommInterface_DirectDependencies.puml!OTHER
!includesub MiddlewareCommLinkManager/MiddlewareCommLinkManager_DirectDependencies.puml!OTHER
!includesub MiddlewareCommDatabaseInterface/MiddlewareCommDatabaseInterface_DirectDependencies.puml!OTHER
!includesub MiddlewareCommInterfaceImplementation/MiddlewareCommInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub MiddlewareCommLinkManagerImplementation/MiddlewareCommLinkManagerImplementation_DirectDependencies.puml!OTHER
!includesub MiddlewareCommDatabaseInterfaceImplementation/MiddlewareCommDatabaseInterfaceImplementation_DirectDependencies.puml!OTHER

@enduml