@startuml DatabaseCommInterfaceImplementationTests

package edu.oakland.test.database {
    class DatabaseCommInterfaceImplementationTests {
        + void rfidInIsRfidOut()
        + void offsetMatchDataPoint()
        + void offsetMatchTrackData()
        + void trackDataInIsTrackDataOut()
        + void modeInIsModeOut()
        + void databaseCommManagerNotNull()
    }
}

@enduml