@startuml DatabaseProductionPackage_InternalDependencies

package edu.oakland.production.database {
    
}

!includesub DatabaseCommInterface/DatabaseCommInterface_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabaseCommManager/DatabaseCommManager_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabaseGisInterface/DatabaseGisInterface_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabaseGisManager/DatabaseGisManager_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabasePersistentStorage/DatabasePersistentStorage_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabaseCommInterfaceImplementation/DatabaseCommInterfaceImplementation_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabaseCommManagerImplementation/DatabaseCommManagerImplementation_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabaseGisInterfaceImplementation/DatabaseGisInterfaceImplementation_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabaseGisManagerImplementation/DatabaseGisManagerImplementation_DirectDependencies.puml!DATABASE_PRODUCTION
!includesub DatabasePersistentStorageImplementation/DatabasePersistentStorageImplementation_DirectDependencies.puml!DATABASE_PRODUCTION

@enduml