@startuml DatabaseProductionPackage_DirectDependencies

package edu.oakland.production.database {
    
}

!startsub DATABASE
!include DatabaseProductionPackage_InternalDependencies.puml
!includesub DatabaseCommInterface/DatabaseCommInterface_DirectDependencies.puml!DATABASE
!includesub DatabaseCommManager/DatabaseCommManager_DirectDependencies.puml!DATABASE
!includesub DatabaseGisInterface/DatabaseGisInterface_DirectDependencies.puml!DATABASE
!includesub DatabaseGisManager/DatabaseGisManager_DirectDependencies.puml!DATABASE
!includesub DatabasePersistentStorage/DatabasePersistentStorage_DirectDependencies.puml!DATABASE
!includesub DatabaseCommInterfaceImplementation/DatabaseCommInterfaceImplementation_DirectDependencies.puml!DATABASE
!includesub DatabaseCommManagerImplementation/DatabaseCommManagerImplementation_DirectDependencies.puml!DATABASE
!includesub DatabaseGisInterfaceImplementation/DatabaseGisInterfaceImplementation_DirectDependencies.puml!DATABASE
!includesub DatabaseGisManagerImplementation/DatabaseGisManagerImplementation_DirectDependencies.puml!DATABASE
!includesub DatabasePersistentStorageImplementation/DatabasePersistentStorageImplementation_DirectDependencies.puml!DATABASE
!endsub

!includesub DatabaseCommInterface/DatabaseCommInterface_DirectDependencies.puml!OTHER
!includesub DatabaseCommManager/DatabaseCommManager_DirectDependencies.puml!OTHER
!includesub DatabaseGisInterface/DatabaseGisInterface_DirectDependencies.puml!OTHER
!includesub DatabaseGisManager/DatabaseGisManager_DirectDependencies.puml!OTHER
!includesub DatabasePersistentStorage/DatabasePersistentStorage_DirectDependencies.puml!OTHER
!includesub DatabaseCommInterfaceImplementation/DatabaseCommInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub DatabaseCommManagerImplementation/DatabaseCommManagerImplementation_DirectDependencies.puml!OTHER
!includesub DatabaseGisInterfaceImplementation/DatabaseGisInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub DatabaseGisManagerImplementation/DatabaseGisManagerImplementation_DirectDependencies.puml!OTHER
!includesub DatabasePersistentStorageImplementation/DatabasePersistentStorageImplementation_DirectDependencies.puml!OTHER

@enduml