@startuml DisplayGpsManagerImplementationTests

package edu.oakland.display01.tests {
    class DisplayGpsManagerImplementationTests {
        + void receivedGpsSignalStrengths()
        + void evaluateGpsSignalStrengths()
        + void acceptableGpsSignalStrengths()
        + void poorGpsSignalStrengths()
        + 
    }
}

@enduml
