@startuml Display01ProductionPackage_InternalDependencies

package edu.oakland.production.display01 {
    
}

!includesub DisplayGpsInterface/DisplayGpsInterface_DirectDependencies.puml!DISPLAY01_PRODUCTION
!includesub DisplayGpsReceiver/DisplayGpsReceiver_DirectDependencies.puml!DISPLAY01_PRODUCTION
!includesub DisplayGpsManager/DisplayGpsManager_DirectDependencies.puml!DISPLAY01_PRODUCTION
!includesub DisplayGpsInterfaceImplementation/DisplayGpsInterfaceImplementation_DirectDependencies.puml!DISPLAY01_PRODUCTION
!includesub DisplayGpsReceiverImplementation/DisplayGpsReceiverImplementation_DirectDependencies.puml!DISPLAY01_PRODUCTION
!includesub DisplayGpsManagerImplementation/DisplayGpsManagerImplementation_DirectDependencies.puml!DISPLAY01_PRODUCTION

@enduml