@startuml Display01ProductionPackage

package edu.oakland.production.display01 {

}

!include DisplayGpsInterface/DisplayGpsInterface.puml
!include DisplayGpsReceiver/DisplayGpsReceiver.puml
!include DisplayGpsManager/DisplayGpsManager.puml
!include DisplayGpsInterfaceImplementation/DisplayGpsInterfaceImplementation.puml
!include DisplayGpsReceiverImplementation/DisplayGpsReceiverImplementation.puml
!include DisplayGpsManagerImplementation/DisplayGpsManagerImplementation.puml

@enduml