@startuml Display01ProductionPackage_DirectDependencies

package edu.oakland.production.display01 {
    
}

!startsub DISPLAY01
!include Display01ProductionPackage_InternalDependencies.puml
!includesub DisplayGpsInterface/DisplayGpsInterface_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsManager/DisplayGpsManager_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsReceiver/DisplayGpsReceiver_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsInterfaceImplementation/DisplayGpsInterfaceImplementation_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsManagerImplementation/DisplayGpsManagerImplementation_DirectDependencies.puml!DISPLAY01
!includesub DisplayGpsReceiverImplementation/DisplayGpsReceiverImplementation_DirectDependencies.puml!DISPLAY01
!endsub

!includesub DisplayGpsInterface/DisplayGpsInterface_DirectDependencies.puml!OTHER
!includesub DisplayGpsManager/DisplayGpsManager_DirectDependencies.puml!OTHER
!includesub DisplayGpsReceiver/DisplayGpsReceiver_DirectDependencies.puml!OTHER
!includesub DisplayGpsInterfaceImplementation/DisplayGpsInterfaceImplementation_DirectDependencies.puml!OTHER
!includesub DisplayGpsManagerImplementation/DisplayGpsManagerImplementation_DirectDependencies.puml!OTHER
!includesub DisplayGpsReceiverImplementation/DisplayGpsReceiverImplementation_DirectDependencies.puml!OTHER

@enduml