@startuml DatabaseCommInterface

package edu.oakland.production.database02 {
    interface DatabaseCommInterface {
        __
        .. Use Case 1 ..
        {abstract} + int receiveGetRfidRequest()
        {abstract} + LocationDataPoint getLocationDataPoint(int offset)
        {abstract} + void storeTrackDataRequest(TrackData trackData)
        .. Use Case 2 ..

    }
}

@enduml