@startuml DisplayComm2WayInterface

package edu.oakland.production.display02 {
    interface DisplayComm2WayInterface {
        __
        .. Use Case 1 ..
        {abstract} + TrackData passRfidRequest(int rfidNum)
    }
}

@enduml
