@startuml DatabaseGisInterfaceStub_Closure

!startsub MIDDLEWARE01_TEST
!include DatabaseGisInterfaceStub.puml
!endsub

!startsub MIDDLEWARE01

!endsub

!startsub OTHER
!include ../../../database/production/DatabaseGisInterface/DatabaseGisInterface_Closure.puml
DatabaseGisInterfaceStub .up.|> DatabaseGisInterface
!endsub

@enduml