@startuml Middleware02TestPackage_DirectDependencies

package edu.oakland.test.middleware02 {
    
}

!startsub MIDDLEWARE02
!include Middleware02TestPackage_InternalDependencies.puml
!includesub MiddlewareCommInterfaceImplementationTests/MiddlewareCommInterfaceImplementationTests_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommLinkManagerImplementationTests/MiddlewareCommLinkManagerImplementationTests_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommDatabaseInterfaceImplementationTests/MiddlewareCommDatabaseInterfaceImplementationTests_DirectDependencies.puml!MIDDLEWARE02
!includesub TrackDataCalculatorTests/TrackDataCalculatorTests_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommLinkManagerStub/MiddlewareCommLinkManagerStub_DirectDependencies.puml!MIDDLEWARE02
!includesub MiddlewareCommDatabaseInterfaceStub/MiddlewareCommDatabaseInterfaceStub_DirectDependencies.puml!MIDDLEWARE02
!includesub DatabaseCommInterfaceStub/DatabaseCommInterfaceStub_DirectDependencies.puml!MIDDLEWARE02
!endsub

!includesub MiddlewareCommInterfaceImplementationTests/MiddlewareCommInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub MiddlewareCommLinkManagerImplementationTests/MiddlewareCommLinkManagerImplementationTests_DirectDependencies.puml!OTHER
!includesub MiddlewareCommDatabaseInterfaceImplementationTests/MiddlewareCommDatabaseInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub TrackDataCalculatorTests/TrackDataCalculatorTests_DirectDependencies.puml!OTHER
!includesub MiddlewareCommLinkManagerStub/MiddlewareCommLinkManagerStub_DirectDependencies.puml!OTHER
!includesub MiddlewareCommDatabaseInterfaceStub/MiddlewareCommDatabaseInterfaceStub_DirectDependencies.puml!OTHER
!includesub DatabaseCommInterfaceStub/DatabaseCommInterfaceStub_DirectDependencies.puml!OTHER

@enduml