@startuml Middleware02TestPackage_InternalDependencies

package edu.oakland.test.middleware02 {
    
}

!includesub MiddlewareCommInterfaceImplementationTests/MiddlewareCommInterfaceImplementationTests_DirectDependencies.puml!MIDDLEWARE02_TEST
!includesub MiddlewareCommLinkManagerImplementationTests/MiddlewareCommLinkManagerImplementationTests_DirectDependencies.puml!MIDDLEWARE02_TEST
!includesub MiddlewareCommDatabaseInterfaceImplementationTests/MiddlewareCommDatabaseInterfaceImplementationTests_DirectDependencies.puml!MIDDLEWARE02_TEST
!includesub TrackDataCalculatorTests/TrackDataCalculatorTests_DirectDependencies.puml!MIDDLEWARE02_TEST
!includesub MiddlewareCommLinkManagerStub/MiddlewareCommLinkManagerStub_DirectDependencies.puml!MIDDLEWARE02_TEST
!includesub MiddlewareCommDatabaseInterfaceStub/MiddlewareCommDatabaseInterfaceStub_DirectDependencies.puml!MIDDLEWARE02_TEST
!includesub DatabaseCommInterfaceStub/DatabaseCommInterfaceStub_DirectDependencies.puml!MIDDLEWARE02_TEST

@enduml