@startuml DatabaseGisManager

package edu.oakland.production.database {
    interface DatabaseGisManager {
        __
        .. Use Case 1 ..
        {abstract} + void passStoreRequest(LocationDataPoint locationDataPoint)
        .. Use Case 2 ..
        {abstract} + void passModeRequest(String mode)
        {abstract} + String passNextSatRequest(String currentSat)
    }
}

@enduml