@startuml DisplayCommInterfaceImplementationTests

package edu.oakland.test.display02 {
    class DisplayCommInterfaceImplementationTests {
        + void isRfidRecieved()
        + void passToComm2WayisNotNull()
    }
}

@enduml
