@startuml Display02TestPackage_InternalDependencies

package edu.oakland.test.display02 {
    
}

!includesub DisplayCommInterfaceImplementationTests/DisplayCommInterfaceImplementationTests_DirectDependencies.puml!DISPLAY02_TEST
!includesub DisplayComm2WayInterfaceImplementationTests/DisplayComm2WayInterfaceImplementationTests_DirectDependencies.puml!DISPLAY02_TEST
!includesub DisplayCommManagerImplementationTests/DisplayCommManagerImplementationTests_DirectDependencies.puml!DISPLAY02_TEST
!includesub TrackDataPlotterTests/TrackDataPlotterTests_DirectDependencies.puml!DISPLAY02_TEST
!includesub DisplayComm2WayInterfaceStub/DisplayComm2WayInterfaceStub_DirectDependencies.puml!DISPLAY02_TEST
!includesub DisplayCommManagerStub/DisplayCommManagerStub_DirectDependencies.puml!DISPLAY02_TEST
!includesub MiddlewareCommInterfaceStub/MiddlewareCommInterfaceStub_DirectDependencies.puml!DISPLAY02_TEST

@enduml