@startuml Display02TestPackage_DirectDependencies

package edu.oakland.test.display02 {
    
}

!startsub DISPLAY02
!include Display02TestPackage_InternalDependencies.puml
!includesub DisplayCommInterfaceImplementationTests/DisplayCommInterfaceImplementationTests_DirectDependencies.puml!DISPLAY02
!includesub DisplayComm2WayInterfaceImplementationTests/DisplayComm2WayInterfaceImplementationTests_DirectDependencies.puml!DISPLAY02
!includesub DisplayCommManagerImplementationTests/DisplayCommManagerImplementationTests_DirectDependencies.puml!DISPLAY02
!includesub TrackDataPlotterTests/TrackDataPlotterTests_DirectDependencies.puml!DISPLAY02
!includesub DisplayComm2WayInterfaceStub/DisplayComm2WayInterfaceStub_DirectDependencies.puml!DISPLAY02
!includesub DisplayCommManagerStub/DisplayCommManagerStub_DirectDependencies.puml!DISPLAY02
!includesub MiddlewareCommInterfaceStub/MiddlewareCommInterfaceStub_DirectDependencies.puml!DISPLAY02
!endsub

!includesub DisplayCommInterfaceImplementationTests/DisplayCommInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub DisplayComm2WayInterfaceImplementationTests/DisplayComm2WayInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub DisplayCommManagerImplementationTests/DisplayCommManagerImplementationTests_DirectDependencies.puml!OTHER
!includesub TrackDataPlotterTests/TrackDataPlotterTests_DirectDependencies.puml!OTHER
!includesub DisplayComm2WayInterfaceStub/DisplayComm2WayInterfaceStub_DirectDependencies.puml!OTHER
!includesub DisplayCommManagerStub/DisplayCommManagerStub_DirectDependencies.puml!OTHER
!includesub MiddlewareCommInterfaceStub/MiddlewareCommInterfaceStub_DirectDependencies.puml!OTHER

@enduml