@startuml MiddlewareGisManagerImplementation_Closure

!startsub MIDDLEWARE01_PRODUCTION
!include MiddlewareGisManagerImplementation.puml

!include ../MiddlewareGisManager/MiddlewareGisManager_Closure.puml
MiddlewareGisManagerImplementation .up.|> MiddlewareGisManager
!endsub

!startsub MIDDLEWARE01

!endsub

!startsub OTHER

!endsub

@enduml