@startuml MiddlewareGisManagerImplementation

package edu.oakland.production.middleware01 {
    class MiddlewareGisManagerImplementation {
        __
        .. Use Case 1 ..

        .. Use Case 2 ..

    }
}

@enduml