@startuml DatabaseTestPackage_InternalDependencies

package edu.oakland.test.database {
    
}

!includesub DatabaseCommInterfaceImplementationTests/DatabaseCommInterfaceImplementationTests_DirectDependencies.puml!DATABASE_TEST
!includesub DatabaseCommManagerImplementationTests/DatabaseCommManagerImplementationTests_DirectDependencies.puml!DATABASE_TEST
!includesub DatabaseGisInterfaceImplementationTests/DatabaseGisInterfaceImplementationTests_DirectDependencies.puml!DATABASE_TEST
!includesub DatabaseGisManagerImplementationTests/DatabaseGisManagerImplementationTests_DirectDependencies.puml!DATABASE_TEST
!includesub DatabasePersistentStorageImplementationTests/DatabasePersistentStorageImplementationTests_DirectDependencies.puml!DATABASE_TEST
!includesub PersistentStorageManagerTests/PersistentStorageManagerTests_DirectDependencies.puml!DATABASE_TEST
!includesub DatabaseCommManagerStub/DatabaseCommManagerStub_DirectDependencies.puml!DATABASE_TEST
!includesub DatabaseGisManagerStub/DatabaseGisManagerStub_DirectDependencies.puml!DATABASE_TEST
!includesub DatabasePersistentStorageStub/DatabasePersistentStorageStub_DirectDependencies.puml!DATABASE_TEST

@enduml