@startuml DatabaseTestPackage_DirectDependencies

package edu.oakland.test.database {
    
}

!startsub DATABASE
!include DatabaseTestPackage_InternalDependencies.puml
!includesub DatabaseCommInterfaceImplementationTests/DatabaseCommInterfaceImplementationTests_DirectDependencies.puml!DATABASE
!includesub DatabaseCommManagerImplementationTests/DatabaseCommManagerImplementationTests_DirectDependencies.puml!DATABASE
!includesub DatabaseGisInterfaceImplementationTests/DatabaseGisInterfaceImplementationTests_DirectDependencies.puml!DATABASE
!includesub DatabaseGisManagerImplementationTests/DatabaseGisManagerImplementationTests_DirectDependencies.puml!DATABASE
!includesub DatabasePersistentStorageImplementationTests/DatabasePersistentStorageImplementationTests_DirectDependencies.puml!DATABASE
!includesub PersistentStorageManagerTests/PersistentStorageManagerTests_DirectDependencies.puml!DATABASE
!includesub DatabaseCommManagerStub/DatabaseCommManagerStub_DirectDependencies.puml!DATABASE
!includesub DatabaseGisManagerStub/DatabaseGisManagerStub_DirectDependencies.puml!DATABASE
!includesub DatabasePersistentStorageStub/DatabasePersistentStorageStub_DirectDependencies.puml!DATABASE
!endsub

!includesub DatabaseCommInterfaceImplementationTests/DatabaseCommInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub DatabaseCommManagerImplementationTests/DatabaseCommManagerImplementationTests_DirectDependencies.puml!OTHER
!includesub DatabaseGisInterfaceImplementationTests/DatabaseGisInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub DatabaseGisManagerImplementationTests/DatabaseGisManagerImplementationTests_DirectDependencies.puml!OTHER
!includesub DatabasePersistentStorageImplementationTests/DatabasePersistentStorageImplementationTests_DirectDependencies.puml!OTHER
!includesub PersistentStorageManagerTests/PersistentStorageManagerTests_DirectDependencies.puml!OTHER
!includesub DatabaseCommManagerStub/DatabaseCommManagerStub_DirectDependencies.puml!OTHER
!includesub DatabaseGisManagerStub/DatabaseGisManagerStub_DirectDependencies.puml!OTHER
!includesub DatabasePersistentStorageStub/DatabasePersistentStorageStub_DirectDependencies.puml!OTHER

@enduml