@startuml DisplayGpsInterfaceStub_DirectDependencies

!startsub ADMIN_TEST
!include DisplayGpsInterfaceStub.puml
!endsub

!startsub ADMIN

!endsub

!startsub OTHER
!include ../../../display01/production/DisplayGpsInterface/DisplayGpsInterface.puml
DisplayGpsInterfaceStub .up.|> DisplayGpsInterface
!endsub

@enduml