@startuml DisplayGpsManagerImplementation

package edu.oakland.production.display01 {
    class DisplayGpsManagerImplementation {
        __
        .. Use Case 1 ..

        .. Use Case 2 ..

    }
}

@enduml