@startuml DatabaseGisInterfaceImplementationTests_Closure

!startsub DATABASE_TEST
!include DatabaseGisInterfaceImplementationTests.puml

!include ../DatabaseGisManagerStub/DatabaseGisManagerStub_Closure.puml
DatabaseGisInterfaceImplementationTests ..> DatabaseGisManagerStub
!endsub

!startsub DATABASE
!include ../../production/DatabaseGisInterfaceImplementation/DatabaseGisInterfaceImplementation_Closure.puml
DatabaseGisInterfaceImplementationTests ..> DatabaseGisInterfaceImplementation
!endsub

!startsub OTHER

!endsub

@enduml