@startuml DatabaseGisInterfaceImplementationTests

package edu.oakland.test.database {
    class DatabaseGisInterfaceImplementationTests {
        + void dataPointInIsDataPointOut()
        + void modeInIsModeOut()
        + void currentSatGetsNextSat()
        + void databaseGisManagerNotNull()
    }
}

@enduml
