@startuml Middleware01Packages_InternalDependencies

!includesub production/Middleware01ProductionPackage_DirectDependencies.puml!MIDDLEWARE01
!includesub test/Middleware01TestPackage_DirectDependencies.puml!MIDDLEWARE01
!includesub helper/Middleware01HelperPackage_DirectDependencies.puml!MIDDLEWARE01

@enduml