@startuml Middleware01TestPackage_InternalDependencies

package edu.oakland.test.middleware01 {
    
}

!includesub MiddlewareGisInterfaceImplementationTests/MiddlewareGisInterfaceImplementationTests_DirectDependencies.puml!MIDDLEWARE01_TEST
!includesub MiddlewareGisProcessorImplementationTests/MiddlewareGisProcessorImplementationTests_DirectDependencies.puml!MIDDLEWARE01_TEST
!includesub MiddlewareGisManagerImplementationTests/MiddlewareGisManagerImplementationTests_DirectDependencies.puml!MIDDLEWARE01_TEST
!includesub MiddlewareGisProcessorStub/MiddlewareGisProcessorStub_DirectDependencies.puml!MIDDLEWARE01_TEST
!includesub MiddlewareGisManagerStub/MiddlewareGisManagerStub_DirectDependencies.puml!MIDDLEWARE01_TEST
!includesub DatabaseGisInterfaceStub/DatabaseGisInterfaceStub_DirectDependencies.puml!MIDDLEWARE01_TEST

@enduml