@startuml Middleware01TestPackage_DirectDependencies

package edu.oakland.test.middleware01 {
    
}

!startsub MIDDLEWARE01
!include Middleware01TestPackage_InternalDependencies.puml
!includesub MiddlewareGisInterfaceImplementationTests/MiddlewareGisInterfaceImplementationTests_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisProcessorImplementationTests/MiddlewareGisProcessorImplementationTests_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisManagerImplementationTests/MiddlewareGisManagerImplementationTests_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisProcessorStub/MiddlewareGisProcessorStub_DirectDependencies.puml!MIDDLEWARE01
!includesub MiddlewareGisManagerStub/MiddlewareGisManagerStub_DirectDependencies.puml!MIDDLEWARE01
!includesub DatabaseGisInterfaceStub/DatabaseGisInterfaceStub_DirectDependencies.puml!MIDDLEWARE01
!endsub

!includesub MiddlewareGisInterfaceImplementationTests/MiddlewareGisInterfaceImplementationTests_DirectDependencies.puml!OTHER
!includesub MiddlewareGisProcessorImplementationTests/MiddlewareGisProcessorImplementationTests_DirectDependencies.puml!OTHER
!includesub MiddlewareGisManagerImplementationTests/MiddlewareGisManagerImplementationTests_DirectDependencies.puml!OTHER
!includesub MiddlewareGisProcessorStub/MiddlewareGisProcessorStub_DirectDependencies.puml!OTHER
!includesub MiddlewareGisManagerStub/MiddlewareGisManagerStub_DirectDependencies.puml!OTHER
!includesub DatabaseGisInterfaceStub/DatabaseGisInterfaceStub_DirectDependencies.puml!OTHER

@enduml