@startuml DatabasePersistentStorageImplementation_Closure

!startsub DATABASE_PRODUCTION
!include DatabasePersistentStorageImplementation.puml

!include ../DatabasePersistentStorage/DatabasePersistentStorage_Closure.puml
DatabasePersistentStorageImplementation .up.|> DatabasePersistentStorage
!endsub

!startsub DATABASE

!endsub

!startsub OTHER

!endsub

@enduml