@startuml DisplayCommInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayCommInterfaceImplementation {
        - DisplayComm2WayInterface receiver
        __
        + DisplayCommInterface(DisplayComm2WayInterface receiver)
        .. Use Case 1 ..
        + TrackData receiveRfidRequest(int rfidNum)
        - TrackData passToComm2WayInterface(int rfidNum)
    }
}

@enduml
