@startuml DisplayCommInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayCommInterfaceImplementation {
        __
        .. Use Case 1 ..

        .. Use Case 2 ..

    }
}

@enduml