@startuml DisplayCommInterfaceImplementation_Closure

!startsub DISPLAY02_PRODUCTION
!include DisplayCommInterfaceImplementation.puml

!include ../DisplayCommInterface/DisplayCommInterface_Closure.puml
DisplayCommInterfaceImplementation .up.|> DisplayCommInterface
!endsub

!startsub DISPLAY02

!endsub

!startsub OTHER

!endsub

@enduml