@startuml DisplayComm2WayInterfaceImplementation_DirectDependencies

!startsub DISPLAY02_PRODUCTION
!include DisplayComm2WayInterfaceImplementation.puml

!include ../DisplayComm2WayInterface/DisplayComm2WayInterface.puml
DisplayComm2WayInterfaceImplementation .up.|> DisplayComm2WayInterface
!endsub

!startsub DISPLAY02

!endsub

!startsub OTHER

!endsub

@enduml