@startuml DisplayComm2WayInterfaceImplementation

package edu.oakland.production.display02 {
    class DisplayComm2WayInterfaceImplementation {
        - DisplayCommManager manager
        __
        + DisplayComm2WayInterfaceImplementation(DisplayCommManager manager)
        .. Use Case 1 ..
        + TrackData passRfidRequest(int rfidNum)
        - void determineUserRequestFormat(int rfidNum)
        - void receiveRequestFromDisplayCommInterface(int rfidNum)
    }
}

@enduml
