@startuml DatabaseCommInterfaceImplementation_DirectDependencies

!startsub DATABASE02_PRODUCTION
!include DatabaseCommInterfaceImplementation.puml

!include ../DatabaseCommInterface/DatabaseCommInterface.puml
DatabaseCommInterfaceImplementation .up.|> DatabaseCommInterface
!endsub

!startsub DATABASE02

!endsub

!startsub OTHER

!endsub

@enduml