@startuml DisplayCommInterfaceStub_DirectDependencies

!startsub ADMIN_TEST
!include DisplayCommInterfaceStub.puml
!endsub

!startsub ADMIN

!endsub

!startsub OTHER
!include ../../../display02/production/DisplayCommInterface/DisplayCommInterface.puml
DisplayCommInterfaceStub .up.|> DisplayCommInterface
!endsub

@enduml