@startuml DatabaseGisInterfaceImplementation

package edu.oakland.production.database {
    class DatabaseGisInterfaceImplementation {
        __
        .. Use Case 1 ..
        + void recieveStoreRequest(LocationDataPoint locationDataPoint)
        .. Use Case 2 ..
        + void recieveModeRequest(String mode)
        + String recieveNextSatRequest(String currentSat)
    }
}

@enduml
