@startuml DemoTests_Closure

!startsub ADMIN_TEST
!include DemoTests.puml
!endsub

!startsub ADMIN
!include ../../production/Demo/Demo_Closure.puml
DemoTests ..> Demo
!endsub

!startsub OTHER

!endsub

@enduml