@startuml MiddlewareGisInterface

package edu.oakland.production.middleware01 {
    interface MiddlewareGisInterface {
        __
        .. Use Case 1 ..
        {abstract} + String revieveGpsSignalStrength(Satellite satelliteSignal)
        .. Use Case 2 ..
        {abstract} + String revieveGpsSignalStrength(Satellite satelliteSignal)
    }
}

@enduml